services:
  # ldap:
  #   image: osixia/openldap:1.5.0
  #   container_name: ldap-server
  #   environment:
  #     - LDAP_ORGANISATION=ExampleOrg
  #     - LDAP_DOMAIN=example.com
  #     - LDAP_ADMIN_PASSWORD=adminpassword
  #     - LDAP_CONFIG_PASSWORD=configpassword
  #   ports:
  #     - "389:389"   # LDAP port
  #     - "636:636"   # LDAPS port (optional, for secure connection)
  #   volumes:
  #     - ldap_data:/var/lib/ldap
  #     - ldap_config:/etc/ldap/slapd.d
  #   networks:
  #     - ldap-network

  postgres:
    image: postgres:14.9
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tst1a
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    networks:
      - ldap-network
    
volumes:
  ldap_data:
  ldap_config:
  postgres_data:

networks:
  ldap-network:
    driver: bridge
